# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
