# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 00:18
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_auto_20171113_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=64),
        ),
    ]
