# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_auto_20171113_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='def_date_range',
            field=models.DurationField(default=datetime.timedelta(28)),
        ),
    ]
