# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 02:39
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0007_userrecord_max_display_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='initial_funds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=64),
        ),
    ]
