# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0008_auto_20171204_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
